=== medizininformatik-initiative/fhir-ontology-generator/test/integration/module/querying_metadata.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://medizininformatik-initiative.de/fdpg/QueryingMetadata/v1/schema",
  "$defs": {
    "coding": {
      "type": "object",
      "properties": {
        "system": {
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "display": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      },
      "required": ["system", "code", "display"],
      "additionalProperties": false
    }
  },
  "title": "QueryingMetadata",
  "description": "A document defining a FHIR resource type specific criterion",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "resource_type": {
      "type": "string"
    },
    "module": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "display": {
          "type": "string"
        }
      },
      "required": ["code", "display"],
      "additionalProperties": false
    },
    "context": {
      "$ref": "#/$defs/coding"
    },
    "term_codes": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/coding"
      }
    },
    "term_code_defining_id": {
      "type": "string"
    },
    "value_defining_id": {
      "type": "string"
    },
    "value_defining_type": {
      "type": "string"
    },
    "value_optional": {
      "type": "boolean"
    },
    "value_type": {
      "type": "string"
    },
    "attribute_defining_id_type_map": {
      "type": "object",
      "$comment": "Use pattern '^((([A-Za-z]+)|(\\((?1)\\)))(\\.[A-Za-z0-9:\\[\\]\\-]+)+)$' with Python 3.11",
      "patternProperties": {
        "^\\(*([A-Za-z]+)(\\.([A-Za-z0-9:\\[\\]\\-]+)\\)?)+$": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "optional": {
              "type": "boolean"
            }
          },
          "required": ["optional"],
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "time_restriction_defining_id": {
      "type": "string"
    }
  },
  "required": ["name", "resource_type", "context"],
  "dependentRequired": {
    "value_defining_id": ["value_optional", "value_type"]
  },
  "additionalProperties": false,
  "allOf": [
    {
      "oneOf": [
        {
          "required": ["term_code_defining_id"]
        },
        {
          "required": ["term_codes"]
        }
      ]
    }
  ]
}

=== medizininformatik-initiative/fhir-ontology-generator/example/icu_new/resources/QueryingMetaData/Koerpertemperatur Harnblase.json
{
    "name": "Koerpertemperatur Harnblase",
    "resource_type": "Observation",
    "context": {
        "system": "fdpg.mii.icu",
        "code": "Koerpertemperatur Harnblase",
        "display": "Koerpertemperatur Harnblase",
        "version": "1.0.0"
    },
    "term_code_defining_id": "Observation.code.coding:sct",
    "time_restriction_defining_id": "Observation.effective[x]"
}

=== medizininformatik-initiative/fhir-ontology-generator/projects/fdpg-ontology/input/cohort_selection_ontology/modules/Medikation/QueryingMetaData/MedicationRequestQueryingMetaData.json
{
  "name": "MedicationRequest",
  "resource_type": "MedicationRequest",
  "module": {
    "code": "mii-cds-medikation",
    "display": "Medikation"
  },
  "context": {
    "system": "fdpg.mii.cds",
    "code": "Medikamentenanordnung",
    "display": "Anordnung von Medikamenten",
    "version": "1.0.0"
  },
  "term_code_defining_id": "(MedicationRequest.medication[x]:medicationReference).code.coding:atcClassDe",
  "time_restriction_defining_id": "MedicationRequest.authoredOn"
}

=== medizininformatik-initiative/fhir-ontology-generator/example/icu_new/resources/QueryingMetaData/Einstellung Ausatmungszeit Beatmung.json
{
    "name": "Einstellung Ausatmungszeit Beatmung",
    "resource_type": "Observation",
    "context": {
        "system": "fdpg.mii.icu",
        "code": "Einstellung Ausatmungszeit Beatmung",
        "display": "Einstellung Ausatmungszeit Beatmung",
        "version": "1.0.0"
    },
    "term_code_defining_id": "Observation.code.coding:sct",
    "time_restriction_defining_id": "Observation.effective[x]"
}

=== medizininformatik-initiative/fhir-ontology-generator/example/icu_new/resources/QueryingMetaData/Linksventrikulaeres Schlagvolumen Durch Indikatorverduennung.json
{
    "name": "Linksventrikulaeres Schlagvolumen Durch Indikatorverduennung",
    "resource_type": "Observation",
    "context": {
        "system": "fdpg.mii.icu",
        "code": "Linksventrikulaeres Schlagvolumen Durch Indikatorverduennung",
        "display": "Linksventrikulaeres Schlagvolumen Durch Indikatorverduennung",
        "version": "1.0.0"
    },
    "term_code_defining_id": "Observation.code.coding:sct",
    "time_restriction_defining_id": "Observation.effective[x]"
}

=== medizininformatik-initiative/fhir-ontology-generator/example/mii_core_data_set/CDS_Module/Onkologie/QueryingMetaData/SystemtherapieQueryingMetaData.json
{
  "name": "Systemtherapie",
  "resource_type": "MedicationStatement",
  "context": {
    "system": "dktk.oncology",
    "code": "Systemtherapie",
    "display": "Systemtherapie",
    "version": "1.0.0"
  },"module": {
    "code": "mii-cds-oncology",
    "display": "Onkologie"
  },
  "term_code_defining_id": "MedicationStatement.medication[x]",
  "attribute_defining_id_type_map": {
    "(MedicationStatement.extension:Intention).value[x]": "",
    "(MedicationStatement.extension:StellungZurOp).value[x]": "",
    "(MedicationStatement.extension:Protokoll).value[x]": ""
  },
  "time_restriction_defining_id": "MedicationStatement.effective[x]"
}

=== medizininformatik-initiative/fhir-ontology-generator/example/icu/resources/QueryingMetaData/Rechtsatrialer Druck.json
{
    "name": "Rechtsatrialer Druck",
    "resource_type": "Observation",
    "context": {
        "system": "fdpg.mii.icu",
        "code": "Rechtsatrialer Druck",
        "display": "Rechtsatrialer Druck",
        "version": "1.0.0"
    },
    "term_code_defining_id": "Observation.code.coding:sct",
    "time_restriction_defining_id": "Observation.effective[x]"
}

=== medizininformatik-initiative/fhir-ontology-generator/example/mii_core_data_set/CDS_Module/Onkologie/QueryingMetaData/GenetischeVarianteQueryingMetaData.json
{
  "name": "GenetischeVariante",
  "resource_type": "Observation",
  "context": {
    "system": "bzkf.dktk.oncology",
    "code": "GenetischeVariante",
    "display": "Genetische Variante",
    "version": "1.0.0"
  },"module": {
    "code": "mii-cds-oncology",
    "display": "Onkologie"
  },
  "term_code_defining_id": "Observation.code.coding",
  "value_defining_id": "Observation.value[x]",
  "time_restriction_defining_id": "Observation.effective[x]"
}

=== medizininformatik-initiative/fhir-ontology-generator/projects/fdpg-ontology/input/cohort_selection_ontology/modules/Onkologie/QueryingMetaData/PrimaerdiagnoseQueryingMetaData.json
{
  "name": "Prim√§rdiagnose",
  "resource_type": "Condition",
  "module": {
    "code": "mii-cds-Onkologie",
    "display": "Onkologie"
  },
  "context": {
    "system": "fdpg.mii.cds",
    "code": "Diagnose",
    "display": "Diagnose",
    "version": "1.0.0"
  },
  "term_code_defining_id": "Condition.code.coding:icd10-gm",
  "time_restriction_defining_id": "Condition.recordedDate",
  "attribute_defining_id_type_map": {
    "Condition.bodySite.coding:primaertumorSeitenlokalisation": {
      "type": "",
      "optional": true
    }
  }
}
