=== medizininformatik-initiative/fhir-ontology-generator/test/integration/module/querying_metadata.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://medizininformatik-initiative.de/fdpg/QueryingMetadata/v1/schema",
  "$defs": {
    "coding": {
      "type": "object",
      "properties": {
        "system": {
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "display": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      },
      "required": ["system", "code", "display"],
      "additionalProperties": false
    }
  },
  "title": "QueryingMetadata",
  "description": "A document defining a FHIR resource type specific criterion",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "resource_type": {
      "type": "string"
    },
    "module": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "display": {
          "type": "string"
        }
      },
      "required": ["code", "display"],
      "additionalProperties": false
    },
    "context": {
      "$ref": "#/$defs/coding"
    },
    "term_codes": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/coding"
      }
    },
    "term_code_defining_id": {
      "type": "string"
    },
    "value_defining_id": {
      "type": "string"
    },
    "value_defining_type": {
      "type": "string"
    },
    "value_optional": {
      "type": "boolean"
    },
    "value_type": {
      "type": "string"
    },
    "attribute_defining_id_type_map": {
      "type": "object",
      "$comment": "Use pattern '^((([A-Za-z]+)|(\\((?1)\\)))(\\.[A-Za-z0-9:\\[\\]\\-]+)+)$' with Python 3.11",
      "patternProperties": {
        "^\\(*([A-Za-z]+)(\\.([A-Za-z0-9:\\[\\]\\-]+)\\)?)+$": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "optional": {
              "type": "boolean"
            }
          },
          "required": ["optional"],
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "time_restriction_defining_id": {
      "type": "string"
    }
  },
  "required": ["name", "resource_type", "context"],
  "dependentRequired": {
    "value_defining_id": ["value_optional", "value_type"]
  },
  "additionalProperties": false,
  "allOf": [
    {
      "oneOf": [
        {
          "required": ["term_code_defining_id"]
        },
        {
          "required": ["term_codes"]
        }
      ]
    }
  ]
}

=== medizininformatik-initiative/fhir-ontology-generator/projects/fdpg-ontology/input/cohort_selection_ontology/modules/Imaging/QueryingMetaData/MII_PR_Bildgebung_RadiologischerBefundberichtSnomedCtQueryingMetaData.json
{
  "name": "MII_PR_Bildgebung_Radiologischer_Befundbericht",
  "context": {
    "code": "Radiologischer Befundbericht",
    "display": "Radiologischer Befundbericht",
    "system": "fdpg.mii.cds",
    "version": "1.0.0"
  },
  "module": {
    "code": "mii-cds-imaging",
    "display": "MII KDS Bildgebung"
  },
  "resource_type": "DiagnosticReport",
  "term_code_defining_id": "DiagnosticReport.code.coding:sct",
  "time_restriction_defining_id": "DiagnosticReport.effective",
  "attribute_defining_id_type_map": {
    "DiagnosticReport.conclusionCode": {
      "type": "",
      "optional": true
    },
    "DiagnosticReport.result": {
      "type": "reference",
      "optional": true
    },
    "DiagnosticReport.study": {
      "type": "reference",
      "optional": true
    }
  }
}

=== medizininformatik-initiative/fhir-ontology-generator/projects/fdpg-ontology/input/cohort_selection_ontology/modules/Onkologie/QueryingMetaData/OperationSCTQueryingMetaData.json
{
  "name": "Operation",
  "resource_type": "Procedure",
  "module": {
    "code": "mii-cds-Onkologie",
    "display": "Onkologie"
  },
  "context": {
    "system": "fdpg.mii.cds",
    "code": "Therapie",
    "display": "Therapie",
    "version": "1.0.0"
  },
  "term_code_defining_id": "Procedure.code.coding:sct",
  "time_restriction_defining_id": "Procedure.performed[x]",
  "attribute_defining_id_type_map": {
    "(Procedure.reasonReference).code.coding:icd10-gm": {
      "type": "reference",
      "optional": true
    }
  }
}

=== medizininformatik-initiative/fhir-ontology-generator/example/bkfz/resources/QueryingMetaData/GradingQueryingMetaData.json
{
  "name": "Grading",
  "resource_type": "Observation",
  "module": {
    "code": "mii-cds-BZKF",
    "display": "BZKF"
  },
  "context": {
    "system": "bzkf.dktk.oncology",
    "code": "Grading",
    "display": "Grading"
  },
  "term_code_defining_id": "Observation.code.coding",
  "value_defining_id": "Observation.value[x]",
  "time_restriction_defining_id": "Observation.effective[x]"
}

=== medizininformatik-initiative/fhir-ontology-generator/example/gecco/resources/QueryingMetaData/ConditionQueryingMetaData.json
{
  "name": "Condition",
  "resource_type": "Condition",
  "module": {
    "code": "mii-cds-gecco",
    "display": "GECCO"
  },
  "context": {
    "system": "fdpg.mii.gecco",
    "code": "Condition",
    "display": "Condition"
  },
  "term_code_defining_id": "Condition.code.coding:icd10-gm",
  "time_restriction_defining_id": "Condition.onset[x]"
}

=== medizininformatik-initiative/fhir-ontology-generator/projects/fdpg-ontology/input/cohort_selection_ontology/modules/Mikrobiologie/QueryingMetaData/MII_PR_Mikrobio_MRGNKlasseQueryingMetaData.json
{
  "context": {
    "code": "Mikrobiologie MRGN-Klasse",
    "display": "Mikrobiologie MRGN-Klasse",
    "system": "fdpg.mii.cds",
    "version": "1.0.0"
  },
  "module": {
    "code": "mii-cds-mikrobio",
    "display": "Mikrobiologie"
  },
  "name": "MRGN-Klasse",
  "resource_type": "Observation",
  "term_code_defining_id": "Observation.code",
  "time_restriction_defining_id": "Observation.effective[x]",
  "value_defining_id": "Observation.value[x]:valueCodeableConcept",
  "value_type": "concept",
  "attribute_defining_id_type_map": {
    "Observation.code": {
      "type": "concept",
      "optional": true
    },
    "(Observation.specimen).type.coding": {
      "type": "reference",
      "optional": true
    }
  }
}

=== medizininformatik-initiative/fhir-ontology-generator/example/icu/resources/QueryingMetaData/Koerpertemperatur rektal.json
{
    "name": "Koerpertemperatur rektal",
    "resource_type": "Observation",
    "context": {
        "system": "fdpg.mii.icu",
        "code": "Koerpertemperatur rektal",
        "display": "Koerpertemperatur rektal",
        "version": "1.0.0"
    },
    "term_code_defining_id": "Observation.code.coding:sct",
    "time_restriction_defining_id": "Observation.effective[x]",
    "value_defining_id": "Observation.value[x]"
}

=== medizininformatik-initiative/fhir-ontology-generator/example/gecco/resources/QueryingMetaData/SnomedConditionQueryingMetaData.json
{
  "name": "SnomedCondition",
  "resource_type": "Condition",
  "module": {
    "code": "mii-cds-gecco",
    "display": "GECCO"
  },
  "context": {
    "system": "fdpg.mii.gecco",
    "code": "Condition",
    "display": "Condition"
  },
  "term_code_defining_id": "Condition.code.coding:sct",
  "time_restriction_defining_id": "Condition.onset[x]"
}

=== medizininformatik-initiative/fhir-ontology-generator/example/icu/resources/QueryingMetaData/Monitoring und Vitaldaten.json
{
    "name": "Monitoring und Vitaldaten",
    "resource_type": "Observation",
    "context": {
        "system": "fdpg.mii.icu",
        "code": "Monitoring und Vitaldaten",
        "display": "Monitoring und Vitaldaten",
        "version": "1.0.0"
    },
    "term_code_defining_id": "Observation.code.coding:sct",
    "time_restriction_defining_id": "Observation.effective[x]"
}
