=== medizininformatik-initiative/fhir-ontology-generator/test/integration/module/querying_metadata.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://medizininformatik-initiative.de/fdpg/QueryingMetadata/v1/schema",
  "$defs": {
    "coding": {
      "type": "object",
      "properties": {
        "system": {
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "display": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      },
      "required": ["system", "code", "display"],
      "additionalProperties": false
    }
  },
  "title": "QueryingMetadata",
  "description": "A document defining a FHIR resource type specific criterion",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "resource_type": {
      "type": "string"
    },
    "module": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "display": {
          "type": "string"
        }
      },
      "required": ["code", "display"],
      "additionalProperties": false
    },
    "context": {
      "$ref": "#/$defs/coding"
    },
    "term_codes": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/coding"
      }
    },
    "term_code_defining_id": {
      "type": "string"
    },
    "value_defining_id": {
      "type": "string"
    },
    "value_defining_type": {
      "type": "string"
    },
    "value_optional": {
      "type": "boolean"
    },
    "value_type": {
      "type": "string"
    },
    "attribute_defining_id_type_map": {
      "type": "object",
      "$comment": "Use pattern '^((([A-Za-z]+)|(\\((?1)\\)))(\\.[A-Za-z0-9:\\[\\]\\-]+)+)$' with Python 3.11",
      "patternProperties": {
        "^\\(*([A-Za-z]+)(\\.([A-Za-z0-9:\\[\\]\\-]+)\\)?)+$": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "optional": {
              "type": "boolean"
            }
          },
          "required": ["optional"],
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "time_restriction_defining_id": {
      "type": "string"
    }
  },
  "required": ["name", "resource_type", "context"],
  "dependentRequired": {
    "value_defining_id": ["value_optional", "value_type"]
  },
  "additionalProperties": false,
  "allOf": [
    {
      "oneOf": [
        {
          "required": ["term_code_defining_id"]
        },
        {
          "required": ["term_codes"]
        }
      ]
    }
  ]
}

=== medizininformatik-initiative/fhir-ontology-generator/projects/fdpg-ontology/input/cohort_selection_ontology/modules/Molgen/disabled/BerichtQueryingMetaData.json
{
  "context": {
    "code": "Molgen",
    "display": "Molgen",
    "system": "fdpg.mii.cds",
    "version": "1.0.0"
  },
  "module": {
    "code": "mii-cds-molgen",
    "display": "Molgen"
  },
  "name": "Bericht",
  "resource_type": "DiagnosticReport",
  "term_code_defining_id": "DiagnosticReport.conclusionCode"
}

=== medizininformatik-initiative/fhir-ontology-generator/example/mii_core_data_set/CDS_Module/ICU/QueryingMetaData/SD_MII_ICU_KoerpergroesseQueryingMetaData.json
{
  "context": {
    "code": "ICU",
    "display": "ICU",
    "system": "fdpg.mii.cds",
    "version": "1.0.0"
  },
  "module": {
    "code": "mii-cds-ICU",
    "display": "ICU"
  },
  "name": "SD_MII_ICU_Koerpergroesse",
  "resource_type": "Observation",
  "term_code_defining_id": "Observation.code.coding:loinc",
  "time_restriction_defining_id": "Observation.effective[x]",
  "value_defining_id": "Observation.value[x]:valueQuantity",
  "value_optional": false
}

=== medizininformatik-initiative/fhir-ontology-generator/projects/fdpg-ontology/input/cohort_selection_ontology/modules/Onkologie/QueryingMetaData/BioprobeQueryingMetaData.json
{
  "name": "Bioprobe",
  "resource_type": "Specimen",
  "module": {
    "code": "mii-cds-Onkologie",
    "display": "Onkologie"
  },
  "context": {
    "system": "fdpg.mii.cds",
    "code": "MII_Onkologie_Bioprobe",
    "display": "MII Onkologie Bioprobe",
    "version": "1.0.0"
  },
  "term_code_defining_id": "Specimen.type",
  "time_restriction_defining_id": "Specimen.collection.collected[x]:collectedDateTime"
}

=== medizininformatik-initiative/fhir-ontology-generator/projects/fdpg-ontology/input/cohort_selection_ontology/modules/Onkologie/QueryingMetaData/PatientGenderQueryingMetaData.json
{
  "name": "Gender",
  "resource_type": "Patient",
  "module": {
    "code": "bzkf-dktk-onkologie",
    "display": "Onkologie"
  },
  "context": {
    "system": "bzkf.dktk.onkologie",
    "code": "Person",
    "display": "Person",
    "version": "1.0.0"
  },
  "term_codes": [
    {
      "system": "http://snomed.info/sct",
      "code": "263495000",
      "display": "Geschlecht"
    }
  ],
  "value_defining_id": "Patient.gender",
  "value_type": "code",
  "value_optional": false
}

=== medizininformatik-initiative/fhir-ontology-generator/example/icu/resources/QueryingMetaData/Inspiratorischer Gasfluss.json
{
    "name": "Inspiratorischer Gasfluss",
    "resource_type": "Observation",
    "context": {
        "system": "fdpg.mii.icu",
        "code": "Inspiratorischer Gasfluss",
        "display": "Inspiratorischer Gasfluss",
        "version": "1.0.0"
    },
    "term_code_defining_id": "Observation.code.coding:sct",
    "time_restriction_defining_id": "Observation.effective[x]",
    "value_defining_id": "Observation.value[x]:valueQuantity"
}

=== medizininformatik-initiative/fhir-ontology-generator/example/icu/resources/QueryingMetaData/Exspiratorischer Sauerstoffpartialdruck.json
{
    "name": "Exspiratorischer Sauerstoffpartialdruck",
    "resource_type": "Observation",
    "context": {
        "system": "fdpg.mii.icu",
        "code": "Exspiratorischer Sauerstoffpartialdruck",
        "display": "Exspiratorischer Sauerstoffpartialdruck",
        "version": "1.0.0"
    },
    "term_code_defining_id": "Observation.code.coding:sct",
    "time_restriction_defining_id": "Observation.effective[x]",
    "value_defining_id": "Observation.value[x]"
}

=== medizininformatik-initiative/fhir-ontology-generator/example/icu/resources/QueryingMetaData/Puls.json
{
    "name": "Puls",
    "resource_type": "Observation",
    "context": {
        "system": "fdpg.mii.icu",
        "code": "Puls",
        "display": "Puls",
        "version": "1.0.0"
    },
    "term_code_defining_id": "Observation.code.coding:sct",
    "time_restriction_defining_id": "Observation.effective[x]",
    "value_defining_id": "Observation.value[x]"
}

=== medizininformatik-initiative/fhir-ontology-generator/example/bkfz_example/resources/QueryingMetaData/TNMpQueryingMetaData.json
{
  "name": "TNMp",
  "resource_type": "Observation",
  "context": {
    "system": "bzkf.dktk.oncology",
    "code": "TNMp",
    "display": "TNMp"
  },
  "term_code_defining_id": "Observation.code.coding",
  "value_defining_id": "Observation.value[x]",
  "attribute_defining_id_type_map": {
    "Observation.component:TNM-T.value[x]": "",
    "Observation.component:TNM-N.value[x]": "",
    "Observation.component:TNM-M.value[x]": "",
    "Observation.component:TNM-y-Symbol.value[x]": "",
    "Observation.component:TNM-r-Symbol.value[x]": "",
    "Observation.component:TNM-m-Symbol.value[x]": ""
  },
  "time_restriction_defining_id": "Observation.effective[x]"
}
